docs:update documentation with data providers - EUBFR-161
ec-europa/eubfr-data-lake pull request #106
Opened 2018-04-05 10:58 UTC by raduchiriac

2018-04-05 12:34 UTC, kalinchernev commented
INFOREGIO XML also has `Project_NUTS2_code`

2018-04-05 12:36 UTC, kalinchernev requested changes
inforegio xls is xml ;)

2018-04-09 07:51 UTC, kalinchernev approved these changes

2018-04-09 07:55 UTC, kalinchernev commented
Changes I added after @raduchiriac 
- stubs from tests are re-used for example data, no need to copy/paste these - error prone and takes more to keep it right
- fields are named to match what we currently have, later when EUBFR-160, these will be renamed as well
- page moved in a separate section because the enrichment topic will grow in future

2018-04-09 09:14 UTC, yhuard approved these changes

2018-04-09 09:15 UTC, merged