feat(iati): init etl
ec-europa/eubfr-data-lake pull request #110
Opened 2018-04-11 08:51 UTC by degliwe

2018-04-11 15:37 UTC, kalinchernev commented
WIP - regression in enrichment manager
So far adding `queueStream.on('end', () => Promise.resolve());` on the custom writeable and/or removing the async from don't help
```
        .on('finish', async () =>
          resolve('All projects have been sent to enrichment')
        );
```

It'll be also nice to add the IATI to https://github.com/ec-europa/eubfr-data-lake/blob/master/docs/enrichment/PRODUCERS_DATA_AVAILABILITY_GRID.md

2018-04-12 06:35 UTC, yhuard requested changes

2018-04-12 06:35 UTC, yhuard commented on services/ingestion/etl/iati/csv/src/events/onParseCSV.js
> +        onError(new Error(`Error on parse: ${e.message}`, reject))
`onError` is async, I guess `e => ` should be async as well

2018-04-12 07:41 UTC, kalinchernev commented
So far I found out that the `CD` code was resolved to a value which was not good for the nominatim service. A pull to the [node-i18n-iso-countries](https://github.com/michaelwittig/node-i18n-iso-countries/pull/86) open for the cases I know are wrong.

2018-04-13 13:44 UTC, yhuard approved these changes

2018-04-13 13:44 UTC, merged