fix(etl): fix budget recording - EUBFR-93
ec-europa/eubfr-data-lake pull request #56
Opened 2017-12-13 13:48 UTC by emeryro

Fix recording of budget for BUDG ETL

2017-12-13 14:21 UTC, emeryro commented
Ready for review

2017-12-13 14:33 UTC, yhuard requested changes

2017-12-13 14:33 UTC, yhuard commented on services/ingestion/etl/budg/xls/src/lib/transform.js
> +      ].replace(',', '')
Will only remove the first `,`. Please use `replace(/,/g,'')`

2017-12-14 06:58 UTC, yhuard approved these changes

2017-12-14 07:01 UTC, merged